const data = [
  {
    title: "Selu Cafe",
    food: [
      {
        dishname: "Ranch Chicken Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Ranch Brown Bread Chicken Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Halumi Bagel",
        dishPic: "images/begel.jpg",
        price: 14,
        calories: "130 Cal",
      },
      {
        dishname: "Pizza Chicken Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Turki Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 15,
        calories: "130 Cal",
      },
      {
        dishname: "Turki Club Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 16,
        calories: "130 Cal",
      },
      {
        dishname: "Salad",
        dishPic: "images/salad.jpg",
        price: 20,
        calories: "120 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 14,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Latte",
        dishPic: "images/latte.jpg",
        price: 16,
        calories: "104 Cal",
      },
      {
        dishname: "Iced Spanish Latte",
        dishPic: "images/latte.jpg",
        price: 16,
        calories: "130 Cal",
      },
      {
        dishname: "Matcha",
        dishPic: "images/matcha.jpg",
        price: 16,
        calories: "130 Cal",
      },
      {
        dishname: "Mojito",
        dishPic: "images/mojito.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Pashion Fruit Smoothie",
        dishPic: "images/mojito.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Mixed Berries Smoothie",
        dishPic: "images/mojito.jpg",
        price: 16,
        calories: "230 Cal",
      },
      {
        dishname: "Cookie",
        dishPic: "images/cookie.jpg",
        price: 7,
        calories: "330 Cal",
      },

      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 2,
        calories: "0 Cal",
      },
      {
        dishname: "RedBall",
        dishPic: "images/redbull.jpg",
        price: 12,
        calories: "130 Cal",
      },
      {
        dishname: "Coka Cola",
        dishPic: "images/cocacola.jpg",
        price: 5,
        calories: "190 Cal",
      },
      {
        dishname: "Lipton Barries",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "130 Cal",
      },
      {
        dishname: "Lipton Peach",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "130 Cal",
      },
      {
        dishname: "Flamin Hot Cheetos Chips Small",
        dishPic: "images/cheetos.jpg",
        price: 3,
        calories: "130 Cal",
      },

      {
        dishname: "Marami Jalapeno",
        dishPic: "images/marami.jpg",
        price: 2,
        calories: "130 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Croissant",
        dishPic: "images/croissant.png",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "7:30 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/selu.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Selu-101",
    location: "Main Building, Second Floor ",
  },
  {
    title: "Saadedin Resturant",
    food: [
      {
        dishname: "Halumi Manqusheh",
        dishPic: "images/sandwich.jpg",
        price: 16,
        calories: "130 Cal",
      },
      {
        dishname: "Pizza",
        dishPic: "images/pizza.jpg",
        price: 12,
        calories: "72 Cal",
      },
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 14,
        calories: "104 Cal",
      },
      {
        dishname: "Taboleh",
        dishPic: "images/salad.jpg",
        price: 12,
        calories: "120 Cal",
      },
      {
        dishname: "Fried Fries",
        dishPic: "images/fries.jpg",
        price: 15,
        calories: "72 Cal",
      },

      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 14,
        calories: "72 Cal",
      },
      {
        dishname: "Red Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },
      {
        dishname: "Iced Latte Medium",
        dishPic: "images/latte.jpg",
        price: 16,
        calories: "104 Cal",
      },
      {
        dishname: "Iced Latte Small",
        dishPic: "images/latte.jpg",
        price: 14,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Spanish Latte",
        dishPic: "images/latte.jpg",
        price: 16,
        calories: "114 Cal",
      },
      {
        dishname: "Mojito",
        dishPic: "images/mojito.jpg",
        price: 16,
        calories: "114 Cal",
      },

      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 2,
        calories: "0 Cal",
      },
      {
        dishname: "RedBall",
        dishPic: "images/redbull.jpg",
        price: 12,
        calories: "150 Cal",
      },
      {
        dishname: "Coka Cola",
        dishPic: "images/cocacola.jpg",
        price: 5,
        calories: "120 Cal",
      },
      {
        dishname: "Lipton Barries",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "100 Cal",
      },
      {
        dishname: "Lipton Peach",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "100 Cal",
      },
      {
        dishname: "Lipton Lemon",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "100 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Halumi Manqusheh",
        dishPic: "images/latte.jpg",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/saadeddin.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Saadeddin-101",
    location: "W Building, Ground Floor",
  },
  {
    title: "Antik Cafe",
    food: [
      {
        dishname: "Liver Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 11.5,
        calories: "140 Cal",
      },
      {
        dishname: "Chicken Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 8.6,
        calories: "140 Cal",
      },
      {
        dishname: "Tuna and Avocado Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 9.2,
        calories: "150 Cal",
      },
      {
        dishname: "Egg and Turki Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 10.35,
        calories: "120 Cal",
      },
      {
        dishname: "Egg and Cheese Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 4.8,
        calories: "160 Cal",
      },
      {
        dishname: "Tahina and Cheese Sandwich",
        dishPic: "images/sandwich.jpg",
        price: 3.6,
        calories: "130 Cal",
      },

      {
        dishname: "Coffee of the Day",
        dishPic: "images/coffee_cup.JPG",
        price: 8,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 3,
        calories: "0 Cal",
      },
    ],
    offers: [
      {
        dishname: "Tea & Chicken Sandwich",
        dishPic: "images/sandwich.jpg",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/antik.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Antik-101",
    location: "W Building, Ground Floor",
  },
  {
    title: "Toss Cafe",
    food: [
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 11.5,
        calories: "130 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 14,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Latte",
        dishPic: "images/latte.jpg",
        price: 14,
        calories: "104 Cal",
      },
      {
        dishname: "Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },

      {
        dishname: "Coffee of the Day",
        dishPic: "images/coffee_cup.JPG",
        price: 8,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 3,
        calories: "0 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Croissant",
        dishPic: "images/croissant.png",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/tosscafe.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Toss-101",
    location: "S Building, Ground Floor",
  },
  {
    title: "Dofaa Cafe",
    food: [
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 11.5,
        calories: "130 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 18,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Latte",
        dishPic: "images/latte.jpg",
        price: 19,
        calories: "104 Cal",
      },
      {
        dishname: "Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },

      {
        dishname: "Americano",
        dishPic: "images/coffee_cup.JPG",
        price: 15,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 5,
        calories: "0 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Croissant",
        dishPic: "images/latte.jpg",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/dofaa89.png",
    rating: 5,
    ratingCount: "5",
    code: "Dofaa-101",
    location: "S Building, Ground Floor",
  },
  {
    title: "Maitre Choux Cafe",
    food: [
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 11.5,
        calories: "130 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 18,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Latte",
        dishPic: "images/latte.jpg",
        price: 19,
        calories: "104 Cal",
      },
      {
        dishname: "Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },

      {
        dishname: "Americano",
        dishPic: "images/coffee_cup.JPG",
        price: 15,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 5,
        calories: "0 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Croissant",
        dishPic: "images/croissant.png",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/maitrechoux.jpeg",
    rating: 5,
    ratingCount: "5",
    code: "Maitre-101",
    location: "W Building, Ground Floor",
  },
  {
    title: "Clazey Cafe",
    food: [
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 11.5,
        calories: "130 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 18,
        calories: "72 Cal",
      },
      {
        dishname: "Iced Latte",
        dishPic: "images/latte.jpg",
        price: 19,
        calories: "104 Cal",
      },
      {
        dishname: "Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },

      {
        dishname: "Americano",
        dishPic: "images/coffee_cup.JPG",
        price: 15,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 5,
        calories: "0 Cal",
      },
    ],
    offers: [
      {
        dishname: "Iced Spanish Latte & Croissant",
        dishPic: "images/croissant.png",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/calzey.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Calzey-101",
    location: "N Building, Ground Floor",
  },
  {
    title: "Mini Market",
    food: [
      {
        dishname: "Croissant",
        dishPic: "images/croissant.png",
        price: 11.5,
        calories: "130 Cal",
      },
      {
        dishname: "Cappuccino",
        dishPic: "images/cappucino.jpg",
        price: 18,
        calories: "72 Cal",
      },

      {
        dishname: "Tea",
        dishPic: "images/tea.jpg",
        price: 8,
        calories: "1 Cal",
      },

      {
        dishname: "Americano",
        dishPic: "images/coffee_cup.JPG",
        price: 15,
        calories: "3 Cal",
      },
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 5,
        calories: "0 Cal",
      },
      ,
      {
        dishname: "Lipton Peach",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "130 Cal",
      },
      {
        dishname: "Flamin Hot Cheetos Chips Small",
        dishPic: "images/cheetos.jpg",
        price: 3,
        calories: "130 Cal",
      },

      {
        dishname: "Marami Jalapeno",
        dishPic: "images/marami.jpg",
        price: 2,
        calories: "130 Cal",
      },
      {
        dishname: "Slash",
        dishPic: "images/slash.jpg",
        price: 2,
        calories: "230 Cal",
      },
    ],
    offers: [
      {
        dishname: "Cheetos & Water",
        dishPic: "images/cheetos.jpg",
        Price: 18,
        calories: "260 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/mini-market.jpg",
    rating: 5,
    ratingCount: "5",
    code: "MiniMarket-101",
    location: "N Building, First Floor",
  },
  {
    title: "Pizza Wow",
    food: [
      {
        dishname: "Water",
        dishPic: "images/water.jpg",
        price: 3,
        calories: "0 Cal",
      },
      ,
      {
        dishname: "Lipton Peach",
        dishPic: "images/lipton.jpg",
        price: 5,
        calories: "130 Cal",
      },
      {
        dishname: "Coka Cola",
        dishPic: "images/cocacola.jpg",
        price: 5,
        calories: "130 Cal",
      },
      {
        dishname: "Pizza",
        dishPic: "images/pizza.jpg",
        price: 30,
        calories: "400 Cal",
      },
    ],
    offers: [
      {
        dishname: "Pizza & Water",
        dishPic: "images/pizza.jpg",
        Price: 20,
        calories: "400 Cal",
      },
    ],
    time: "8:00 AM - 4:00 PM",
    pickup: true,
    isOpen: true,
    logoUrl: "images/pizza.jpg",
    rating: 5,
    ratingCount: "5",
    code: "Pizza-101",
    location: "W Building, Ground Floor",
  },
];

module.exports = data;
